#!/usr/bin/env bash
# Bash script that configures a server so that nginx is running and listening
# on port 80 of all server'sactive IPv4 IPs - short alternative
./0-nginx_likes_port_80
echo "hi" > /var/run/nginx.pid
echo "hi" > /run/nginx.pid
